language: node_js
node_js:
  - 10
deploy:
  provider: heroku
  api_key:
    secure: mBYF4M8f8frn8X5oGLk/JXT+X0sWYYQSPY4HzWJXAje3BRVZf4CghAx5lC4VRQYb4+t1Aol/5Uj3ymrIkbiq2onrYExVssoSY3twbZ7Qyc5aG4WQBocH1aEzvkqhJONS7RD984UiBXDhwilPQCCQwoFsQxpXyR6BV1x+SyHicuIisvD/gks6xbZ/coTeHwXBqUTgDhvQYhasPYad9xlVpXt6RKT6meO7Mlj76zAytPFNiKEkNqRVjmj4d/6bbEqH7gAP8KX7WEdo/RyGlD6sVY45/4J59X64bMFkMDbfyI/kkIgMn3X3H8FhX+9Rg84qv5xjMhIY3tMhjXvndals3bRhml1wa6bTHeBjN8sKNtkvE1QNYP5qzB07NIBVVVdrfm2N6mLzTeCPdZ5+SbEgu24fWs7NSDkOEw7o/qjBjk9BO+g9XAiLT2a3NECmn3OosyB+ReF9zlLWeHXnwMvPAFdiyLw4o8oTIYSNW/ChksF/YXhP+ZWZiaweKB1ymozOIWv21zfgbeHIJrDEsNYHtUUIwqbVU9JuAguG/C3bXrm4AqQudPcDH7kmuXHPK0PKWg5KOGNO7hAK5IZaLaMDMnd9WQLqJgEY00X/hBQzDsyyKF2miaznMSoWQ4YleWcahrU2iMmo2U23zwhWiEXG1e2AgNJHIwcKlxTZGdUhai0=
