version: "3.6"
services:
  web:
    build: .
    volumes:
      - .:/app/
      - /app/node_modules
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/sample_api_dev
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  postgres:
    image: postgres:10.4
    ports:
      - "35432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./postgres-initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: sample_api_dev
